#!/usr/bin/env bash
# this is a very cool comment jeje

restart() {
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
        echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}
start() {
	./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
}
stop() {
        kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
        echo "manage_my_process stopped"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
	restart
        ;;
  *)
        echo "Usage: manage_my_process {start|stop|restart}"
esac
