#!/usr/bin/env bash
IFS=:
while read -r user pass userid groupid useridinfo home cmd
do
	printf "The user $user is part of the $groupid gang, lives in $home and rides $cmd. $userid's place is protected by the passcode $pass, more info about the user here: $useridinfo\n"
done < /etc/passwd
