#!/usr/bin/env bash
# this is a very cool comment to this code

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "good luck"
    elif [ $i -eq 4 ]
    then
        echo "bad luck"
    else
	    echo "Holberton School"
	fi
	((i=i+1))
done
