#!/usr/bin/env bash

FILE="holbertonschool"
if [ -e ./$FILE ];
then
    echo "$FILE file exists"
	if [ ! -s ./$FILE ];
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ ! -d ./$FILE ];
	then
		echo "$FILE is a regular file"
	fi
else
    echo "$FILE file does not exist"
fi
